version: '3.8'

volumes:
  db-config:
  db-data:
    name: db-data

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html

  server:
    build:
      context: ./backend/
    container_name: server
    restart: "on-failure"
    expose:
      - 8080
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    image: mysql:8.4.2
    container_name: db
    ports:
      - "5500:3306"
    restart: always
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    networks:
      - default


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass $$REDIS_PASSWORD
    restart: always
    expose:
      - 6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf

  generate_image:
    build:
      context: ./python/AI
    env_file:
      - ./.env
    container_name: generateImage
    restart: "always"
    ports:
      - "5000:5000"
    volumes:
      - './python/AI:/app'
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0 --port=5000


  recommender:
    build:
      context: ./python/recommender/models
    container_name: recommender
    restart: "always"
    ports:
      - "5001:5001"
    volumes:
      - './python/recommender/models:/app'
    environment:
      FLASK_ENV: development
      FLASK_APP: recommender.py
    command: flask run --host=0.0.0.0 --port=5001
