version: '3.8'

volumes:
  db-config:
  db-data:
    name: db-data

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - server
    networks:
      - default

  server:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: server
    restart: "on-failure"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
    stdin_open: true
    depends_on:
      - db
      - redis
    tty: true
    networks:
      - default

  db:
    image: mysql:8.4.2
    container_name: db
    ports:
      - "5500:3306"
    restart: always
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    networks:
      - default


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default


  generate_image:
    build:
      context: ./python/AI
    env_file:
      - ./.env
    container_name: generateImage
    restart: "always"
    ports:
      - "5000:5000"
    volumes:
      - './python/AI:/app'
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - default


  recommender:
    build:
      context: ./python/recommender/models
    container_name: recommender
    restart: "always"
    ports:
      - "5001:5001"
    volumes:
      - './python/recommender/models:/app'
    environment:
      FLASK_ENV: development
      FLASK_APP: recommender.py
    command: flask run --host=0.0.0.0 --port=5001
    networks:
      - default


networks:
  default:
    driver: bridge
